# Book settings
title: INFO183 An√°lisis de sistemas lineales
author: Pablo Huijse Heise 
logo: logo.png

execute:
  execute_notebooks: cache
  cache: _notebooks_cache

parse:
  myst_extended_syntax: true

repository:
  url: https://github.com/phuijse/UACH-INFO183

html:
  home_page_in_navbar: false
  use_repository_button: false
  use_issues_button: false
  use_edit_page_button: false

sphinx:
  extra_extensions: [bokeh.sphinxext.bokeh_plot]
  config:
    language: es

latex:
  latex_documents:
    targetname: book.tex
